### PR TITLE
Allow leaf decay of diagonally-connecting Tropicraft leaves.

### PR DESCRIPTION
**Pull request by bconlon1**
## Leaf Changes
This reworks `TropicraftLeavesBlock` to have additional functionality for triggering neighbor block updates of matching leaf block types in the 3x3 region around a block outside of the normal 6 neighbor directions. 

This allows certain leaves like Palm Leaves to properly decay from Palm Trees.

The possible additional block updates are limited to specific offsets and specific blocks and are handled similarly to how vanilla does regular neighbor updates. The implementation _should_ be fairly performant, but I could be missing something.

## Tree Changes
The palm and rainforest tree features have also undergone some changes so that naturally-generating ones will have their leaf blocks updated to have the correct distance states as opposed to defaulting to 7 and decaying.

Tall rainforest trees have had to have some additional changes to add branches under their canopies due to their size going beyond what is allowed for leaves to not decay, which may require some design input. If this is not liked, then a possible alternative solution could be having a rainforest leaf block with an extended maximum distance.
image

### CODE REVIEW

**Comment by Dragon-Seeker** [comment]
Here to chime in but there are various issues with this implementation as pictured below:

Trees start to decay before such have been even chopped down which may be fixable when the trees are generated as I need to do some sort of processing with my 1.18.2 implementation:






Big trees like the kapok will not fully decay when logs are removed. This one comes down to needing to count indirect blocks as a distance increase of 2 instead of one I believe. This also has the side effect of needing to increase the distance amount specifically as that was needed in my earlier attempt to handle the bigger tree shapes



Here is a [link](https://github.com/Dragon-Seeker/Tropicraft/tree/1.18.2-Experimental-Tree-Decay) to my version which I recommend not directly copying or even using but may be helpful idk.

**Comment by bconlon1** [comment]
Weird, when I had tried testing to see if any trees would start decaying naturally I didn't run into the issue. Maybe it was because I had only tested with sapling-grown trees?

**Comment by bconlon1** [comment]
Okay this does seem to be an issue with naturally grown trees, interesting.

**Comment by Gegy** [comment]
Thank you so much for this PR! This is a really nice solution - and the change to the big trees with the branches looks really nice imo :) 

I've merged this manually in bb8c9a63ea1843d4dbce31f70d45079d1c3c18fb with a couple of small code-style bits and pieces - thanks again, and apologies for taking a while to look at it!

**Pull request closed without merging**
