### PR TITLE
[1.18.2] Add Ability To have Tropicraft Furniture Entities be Invulnerable

### LINKED ISSUE #493: Allow Tropicraft Chairs, Beach Umbrellas & Beach Floats to be Invulnerable

### PR DESCRIPTION
**Pull request by Dragon-Seeker**
Do so by clicking them with a debug stick to toggle such or spawning with the NBT tag enabled which should fix #493

### CODE REVIEW

**Review by NotActuallyTerry — APPROVED** [review]
Works well! Only minor nitpick is:
If you spawn an entity with `{Invulnerable:1}`, you can't undo that with the Debug Stick. Oh well.

**Comment by Dragon-Seeker** [comment]
> Works well! Only minor nitpick is: If you spawn an entity with `{Invulnerable:1}`, you can't undo that with the Debug Stick. Oh well.

Weird limitation, ill take a look real quick to find the source for such.

**Comment by Dragon-Seeker** [comment]
@NotActuallyTerry Are you referring to the tropicraft furniture or other entities? 

Cause that is Minecraft's own flag for invulnerability which is different from this PR as it is intended to create full invulnerability to even prevent people with creative to break the entity unless you use the debug stick to deactivate such and such is only applied to the furniture entity's.

Though I just noticed the nbt key is the exact same as vanilla so I will be changing it to `FullyInvulnerable` to remove overlap and confusion if need be.

**Comment by NotActuallyTerry** [comment]
That's referring to Tropicraft entities, so I think /spawn used the Minecraft invulnerability system then.

**Pull request merged**
