### PR TITLE
[1.18.2] Add wood varaint blocks (Stripped logs, Pressure plates, Buttons, and Signs)

### LINKED ISSUE #481: Signs for Tropicraft Woods
[LT Discord](https://canary.discord.com/channels/444746940761243652/992797246234038332/997877489168818257)

### LINKED ISSUE #494: Ensure all Tropicraft Woods have stripped logs, pressure plates, buttons, and signs

### PR DESCRIPTION
**Pull request by Dragon-Seeker**
Should close #481 and #494 but is unfinished

Will need Stripped Log's side texture and will need some artist to polish the Sign textures for both Bamboo and Thatch.

Blocks to be Added:

[ ] - Still needing to be done
[T] - Needs textures
[?] - Needed Polish on the texture front
[x] - Done 

1. Mahogany
  [x] Button
  [x] Pressure Plate
  [x] Sign Block Entity
  [T] Sign Item
  [T] Stripped Log

2. Palm
  [x] Button
  [x] Pressure Plate
  [x] Sign Block Entity
  [x] Sign Item
  [x] Stripped Log

3. Mangrove
  [x] Button
  [x] Pressure Plate
  [x] Sign Entity
  [x] Sign Item
  [x] ~~Stripped Log~~ *Already Exists*

4. Bamboo
  [x] Button 
  [x] Pressure Plate
  [?] Sign Block Entity
  [x] Sign Item

5. Thatch
  [x] Button 
  [x] Pressure Plate
  [?] Sign Block Entity
  [x] Sign Item

### CODE REVIEW

**Comment by mrhelium3** [comment]
mangrove

Mangrove Sign texture

**Comment by Dragon-Seeker** [comment]
Would like to ask if there should be three different textures for the Mangrove sign since there are three different log variants? 

I have done a demo of this with the commit and my idea was to add the logs within the crafting recipe or something or allow for the bark to be changed with a axe like stripped logs.
java_Dcc6INiZ2X

**Comment by NotActuallyTerry** [comment]
When I read the idea I thought "hell no", but those kinda look nice tbh
@Cojomax99 @SuperCoder7979 thoughts?

**Comment by NotActuallyTerry** [comment]
I'm gonna override them and say that I like it, and it should go in

**Comment by NotActuallyTerry** [comment]
Sign items from @HexabluDEV

Thatch sign: 

Palm sign: 

Bamboo sign: 

Red Mangrove sign: 

Mangrove sign: 

Black Mangrove sign:

**Comment by NotActuallyTerry** [comment]
From @HexabluDEV

Palm stripped logs:  

Palm sign:

**Comment by NotActuallyTerry** [comment]
- Mahogany & Palm sign requires white text, contrast of Mangrove & Bamboo signs need reviewing
- Palm log doesn't strip with axe

**Comment by NotActuallyTerry** [comment]
Added in commits f3bb91b 69f21e3 and 5a71bc5

**Pull request closed without merging**
