### PR TITLE
potential fix for the remote wand client crash

### PR DESCRIPTION
**Pull request by Vectrobe**
replace appropriately, I'm only on the web client atm so I cant verify validity

### CODE REVIEW

**Comment by Vectrobe** [comment]
whoops https://github.com/Tropicraft/Tropicraft/issues/320

**Comment by tterrag1098** [comment]
That's not valid java.

**Comment by Vectrobe** [comment]
hence the description

**Comment by Vectrobe** [comment]
should be right now if you re-open

**Comment by medsouz** [comment]
Code should be fully tested before submitting a pull request. You should setup a workspace and validate your fix works before reopening the issue.

**Comment by Vectrobe** [comment]
...which is what I've done every other time, this is just a suggestion patch I made when I was out...

**Comment by Vectrobe** [comment]
commits will not merge on closed PR's

**Comment by tterrag1098** [comment]
I don't believe this is the right fix either. When would the server be null at runtime? If the code is running on a logical client in a multiplayer game, it should not get this far, and probably should not be running on the logical client at all.

**Comment by Vectrobe** [comment]
The server is null when it doesn't exist, such is the case with a client attached to a remote server, hence why #320 is an issue on remote servers.

**Comment by Vectrobe** [comment]
an alternative is to practically re-write the whole file, although there's not much point now to do that for 1.12

**Pull request closed without merging**
