### PR TITLE
Clean Up and Fix Client Class Loading issue

### PR DESCRIPTION
**Pull request by Dragon-Seeker**
Also Update mappings, forge loader and remove jcenter. With that came fixes to nbt tag method changes also.

### CODE REVIEW

**Comment by Cojomax99** [comment]
I think the Optimize Imports commit can be dropped - it greatly increases the scope of the PR and doesn't feel entirely needed? Not sure what others think.

**Comment by Dragon-Seeker** [comment]
I did such as a test to see if a wrong import existed that was loading client class but found it not to be the issue so such could be dropped

**Comment by Dragon-Seeker** [comment]
Would recommend down the road before release or some time in the future as there was a lot of unused imports though

**Comment by Dragon-Seeker** [comment]
> I think the Optimize Imports commit can be dropped - it greatly increases the scope of the PR and doesn't feel entirely needed? Not sure what others think.

The deed is done, just took some time on how to drop a the two commits and then force-push the changes as it is the only way to do such

**Comment by Tamaized** [comment]
> wrong import existed that was loading client class

For the record, this is impossible. Imports do not exist in bytecode. They're hints for your IDE and that's it. They cannot and will not classload even with some kind of aggressive scanner in the environment.

**Comment by Dragon-Seeker** [comment]
> > wrong import existed that was loading client class
> 
> For the record, this is impossible. Imports do not exist in bytecode. They're hints for your IDE and that's it. They cannot and will not classload even with some kind of aggressive scanner in the environment.

Found such out after doing such, was the main reason I dropped it after cojo sayed something about it.

**Comment by Gegy** [comment]
Merged in https://github.com/Tropicraft/Tropicraft/commit/5c471ba4e0697a57273596483bd93567986860e8. Thank you so much! :)

**Pull request closed without merging**
