### PR TITLE
Fix the memory leak with Beach Floats

### PR DESCRIPTION
**Pull request by Vectrobe**
yea, new model each render would definitely leak...

also other optimisations

### CODE REVIEW

**Comment by Vectrobe** [comment]
shush, I haven't done java in a while...

**Review by Corosauce — APPROVED** [review]
Great catches, new Model per render tick is definitely a no no, the others look like good optimizations too.

**Comment by tterrag1098** [comment]
Post mortem:

The only leak fixed here was the per-render model allocation, though not for the obvious reason.

Simply creating an object every render is wasteful, but not leaky. Such a leak (outside the JVM) requires some native code to be run in an unsafe way, without proper cleanup. I did some digging and found the cause in `ModelRenderer`.

When a `ModelRenderer` is drawn for the first time, it creates a new GL displaylist for itself. There are *no* code paths that ever delete this display list. Not by GC, not manually. The assumption is that models are create-once, and this is true everywhere at least in vanilla. I don't think this is really a vanilla bug since it works for their purposes, but it's definitely something that forge might want to adjust.

So I adjusted (and combined) your commits while keeping you author to only fix the relevant part of code. A more general rendering cleanup would need to be applied to ALL rendering classes (the code you edited is copied across all three colored entity renderers).

See: https://github.com/Tropicraft/Tropicraft/commit/043bca281c18e8dc25759f493b098b238bd96349

**Comment by Vectrobe** [comment]
Yes, the 'vanilla' ModelRenderer is indeed broken and non-compliant, if you were to run it through a GL debugger you'll get a stack of faults in regards to memory leaking.

Allocating to the JVM is bad as well in the sense that it creates unnecessary instructions and GC cycles, which of course would slow down the game. Similar story for things like the stacked colour calls that can prevent SSE optimisation.

I'm going to be looking through for optimisations throughout at some point, though it may end up as a fairly large commit if I do it all in one hit...

**Comment by tterrag1098** [comment]
Creating a lot of objects is wasteful yes, but java's escape analysis is very good and an object that is purely scoped within a single method would be garbage collected nearly instantaneously.

**Pull request merged**
