### PR TITLE
The great block/item ID and localization cleanup

### PR DESCRIPTION
**Pull request by tterrag1098**
Unifying names to a consistent style, removing all the colons in localization, and combining blocks into meta variants where possible/feasible.

### CODE REVIEW

**Comment by tterrag1098** [comment]
[Block ID / Unloc name pass](https://trello.com/c/Yjqmrdml/72-block-id-unloc-name-pass)

**Comment by Cojomax99** [comment]
- Thatch and bamboo bundle drops are incorrect
- Thatch stairs are rotated 90 degrees from the correct angle
- Pineapple, iris, chairs, umbrellas, and sea urchin roe are missing properly mapped names

**Comment by tterrag1098** [comment]
All those fixed and one last thing, I made the shells into meta variants :)

**Review by Cojomax99 — APPROVED** [review]
🎉

**Pull request merged**
