### PR TITLE
zh_CN.lang

### PR DESCRIPTION
**Pull request by DYColdWind**

### CODE REVIEW

**Comment by Cojomax99** [comment]
Is this complete? And are you a native speaker?

**Comment by DYColdWind** [comment]
No, my native language is Chinese.
Also, in minecraft. As long as you have a little foundation you can get involved in translation...
You can see my contribution...

**Comment by DYColdWind** [comment]
Suddenly I realized that I misunderstood what you mean
I thought you asked me，is English my native language?so ...
Yes, zh_cn is Chinese. That is my mother tongue.
In addition, it is still a bit incomplete.
But the rest of the words I really do not know how to translate
However, I believe I will work hard to perfect it in the future，In the future.
sorry...

**Review by tterrag1098 — DISMISSED** [review]

**Comment by tterrag1098** [comment]
Could you please fast-forward this branch to the latest 1.12.2 to avoid conflicts?

**Comment by tterrag1098** [comment]
Nevermind, I can do it myself apparently!

**Pull request closed without merging**
