### PR TITLE
enables wall ornaments again

### PR DESCRIPTION
**Pull request by cbaakman**
Re-enables these traditional tropicraft features:
- shells and masks can hang on the wall
- lost mask entities drop mask items
- mask items can be worn by the player as head gear (custom rendering model)

### CODE REVIEW

**Comment by Cojomax99** [comment]
Could you remove the `.EntityLostMask.java.swp` file from the PR please?

Looks good otherwise :smile:

**Comment by Cojomax99** [comment]
Fixes #82

**Comment by cbaakman** [comment]
It should be removed now in https://github.com/Tropicraft/Tropicraft/pull/109/commits/5f7e7a96fdf9d57293f5fec89add8339520cc87f

**Comment by Nightreaver** [comment]
yeah.. stuck exactly with this issue when compiling master(6.0.6) ... should be merged too!

**Pull request merged**
