### PR TITLE
Bamboo Spear now usable

### PR DESCRIPTION
**Pull request by baguchi**
This pull request make full functionaly spear!

here is change:
Spear is now throwable(like trident but less damage)
add spear projectile entity
also work with enchantment!(like trident)

### CODE REVIEW

**Comment by tterrag1098** [comment]
Thanks! This looks really cool. I'm not sure we want to support riptide though, it doesn't really fit as an enchantment for such a low tech weapon. @Cojomax99 thoughts?

**Comment by Dragon-Seeker** [comment]
> Thanks! This looks really cool. I'm not sure we want to support riptide though, it doesn't really fit as an enchantment for such a low tech weapon. @Cojomax99 thoughts?

May be possible to have a upgraded version of the spear in which can take the enchantment or give it new enchantment designed around the tropics. 

I had thought about in the past giving it the ability for being tipped like arrows with a certain amount of hits before the potion  effect would wear off to prevent it to be overpowered due to its easy re-usability.

**Comment by NotActuallyTerry** [comment]
Hey there!

We've been discussing this internally, and we feel it'd be better withholding Riptide from the basic Bamboo Spear. We're looking into possibly adding higher classes of spears which would allow enchanting with Riptide.

If you remove the ability to enchant the Spear with Riptide, I can go ahead and merge this for you!

**Comment by baguchi** [comment]
fixed it :)

**Review by NotActuallyTerry — APPROVED** [review]
Ran great during my testing!

**Pull request merged**
