### PR TITLE
Coconut spawn

### PR DESCRIPTION
**Pull request by cbaakman**
Makes coconuts spawn under existing palm trees over time.

### CODE REVIEW

**Comment by Cojomax99** [comment]
Why did you change the material of BlockBundle? Not really relevant in this PR :) also, you should check to see if BlockBundle is used by something that isn't a plant. I vaguely recall using it more than once, but I could be wrong.

**Comment by Cojomax99** [comment]
Also, I like this PR but you should add a random.nextInt check so that the spawning of coconuts isn't happening every time the random tick happens. Make it more infrequent by just a bit.

**Comment by cbaakman** [comment]
Sorry for the random block changes, my bad!

The "spawnCoconuts" already has a random.nextInt in it doesn't it?
Frequency can be set as the 6th argument of that function. It's 5 in my case, meaning a spawn chance of 1 in 5.

**Comment by Cojomax99** [comment]
@cbaakman are you going to re-PR this? I liked the idea of this PR :)

**Comment by cbaakman** [comment]
OK, but what exactly do you want to change? Do you want an extra randomization in it? In it's current state I'd think there's a 1 in 5 chance per tick of spawning coconuts.

**Comment by Cojomax99** [comment]
Ah, I forgot the spawnCoconuts method had that chance variable. Sorry, didn't see that for some reason. Looks good!

**Pull request closed without merging**
